In [1]:
import numpy as np
import pandas as pd

In [2]:
b = np.array([[1, 2], [3, 4]])
np.tile(b, (1, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [3]:
import numpy as np

# 示例 1: 两个数组的元素级乘法
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result1 = np.multiply(array1, array2)

# 示例 2: 与标量的乘法
scalar = 10
result2 = np.multiply(array1, scalar)

# 示例 3: 广播机制
array3 = np.array([[1, 2, 3], [4, 5, 6]])
scalar2 = 2
result3 = np.multiply(array3, scalar2)

# 示例 4: 在矩阵乘法中的应用
# 先通过元素级乘法处理矩阵的每个元素，然后用 np.sum 或其他函数处理结果
# 注意：这不是矩阵乘法的标准做法，仅作为 np.multiply 在矩阵操作上应用的示例
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 0], [1, 2]])
element_wise_multiplication = np.multiply(matrix1, matrix2)

result4 = np.sum(element_wise_multiplication, axis=1)

result1, result2, result3, result4


(array([ 4, 10, 18]),
 array([10, 20, 30]),
 array([[ 2,  4,  6],
        [ 8, 10, 12]]),
 array([ 2, 11]))

In [4]:

weight_normaliezed = np.array([[0.1, 0.2, 0.7], [0.3, 0.4, 0.3], [0.5, 0.3, 0.2]])
values = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.multiply(weight_normaliezed, values))
np.multiply(weight_normaliezed, values).sum(axis=1)
# np.multiply(np.sqrt(weight_normaliezed).reshape([1,-1]), values)


[[0.1 0.4 2.1]
 [1.2 2.  1.8]
 [3.5 2.4 1.8]]


array([2.6, 5. , 7.7])

In [5]:
print(weight_normaliezed)
pd.DataFrame(weight_normaliezed)

[[0.1 0.2 0.7]
 [0.3 0.4 0.3]
 [0.5 0.3 0.2]]


0    1    2
0  0.1  0.2  0.7
1  0.3  0.4  0.3
2  0.5  0.3  0.2

In [28]:
print(weight_normaliezed.sum(axis=1))
pd.DataFrame(weight_normaliezed).sum(axis=0)

[1. 1. 1.]


0    0.9
1    0.9
2    1.2
dtype: float64

In [44]:
pd.DataFrame(np.sqrt(weight_normaliezed).reshape(-1, 1)).values.reshape(-1, 3)

array([[0.31622777, 0.4472136 , 0.83666003],
       [0.54772256, 0.63245553, 0.54772256],
       [0.70710678, 0.54772256, 0.4472136 ]])

In [12]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2']})

df2 = pd.DataFrame({'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df1['key'] = 0
df2['key'] = 0

df = pd.merge(df1, df2, on='key').drop('key', axis=1)
print(df1.merge(df2, how='cross'))
df


    A   B  key_x   C   D  key_y
0  A0  B0      0  C0  D0      0
1  A0  B0      0  C1  D1      0
2  A0  B0      0  C2  D2      0
3  A1  B1      0  C0  D0      0
4  A1  B1      0  C1  D1      0
5  A1  B1      0  C2  D2      0
6  A2  B2      0  C0  D0      0
7  A2  B2      0  C1  D1      0
8  A2  B2      0  C2  D2      0


A   B   C   D
0  A0  B0  C0  D0
1  A0  B0  C1  D1
2  A0  B0  C2  D2
3  A1  B1  C0  D0
4  A1  B1  C1  D1
5  A1  B1  C2  D2
6  A2  B2  C0  D0
7  A2  B2  C1  D1
8  A2  B2  C2  D2

In [11]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2']})

df2 = pd.DataFrame({'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})
df1.merge(df2, how='cross')

A   B   C   D
0  A0  B0  C0  D0
1  A0  B0  C1  D1
2  A0  B0  C2  D2
3  A1  B1  C0  D0
4  A1  B1  C1  D1
5  A1  B1  C2  D2
6  A2  B2  C0  D0
7  A2  B2  C1  D1
8  A2  B2  C2  D2